server:
  port: 8080
logging:
  config: classpath:logback-spring-prod.xml

spring:
  config:
    activate:
      on-profile: prod
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  application:
    name: ecommerce
  datasource:
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://mariadb.cjq82ikaejvr.ap-northeast-2.rds.amazonaws.com:3306/project2?useUnicode=true&characterEncoding=UTF-8
  jpa:
    #database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    open-in-view: false

jwt:
  secret-key-source: ${JWT_SECRET_KEY}

cloud:
  aws:
    s3:
      buckets:
        bucket1:
          name: project2-profile
        bucket2:
          name: project2-book
    credentials:
      access-key: ${ACCESS-KEY}
      secret-key: ${SECRET-KEY}
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false